name: fluxus
channels:
  - conda-forge
  - bcg_gamma
  - defaults
dependencies:
  # Python version
  - python                   ~= 3.11
  - pip
  # Additional libraries
  - aiofiles
  - gamma-pytools            ~= 3.0rc1
  - pandas
  - python-dotenv
  - PyYAML
  - toml
  # Graphviz
  - graphviz                 ~= 9.0
  - python-graphviz
  - pytorch
  - transformers
  # pip-only dependencies
  # - pip:
      # Optional LLM supoprt packages:
      # - anthropic
      # - google-generativeai
      # - huggingface_hub
      # - openai
      # - qroq
  # sphinx
  - nbsphinx                 ~= 0.9
  - sphinx                   ~= 7.2
  - sphinx-autodoc-typehints ~= 1.19
  - pydata-sphinx-theme      ~= 0.8.1
  - packaging                
  # notebooks
  - ipywidgets               ~= 8.0
  - jupyterlab               ~= 4.0
  - notebook                 ~= 7.0
  # devops
  - pytest                   ~= 8.0
  - pytest-asyncio
  - pytest-cov
  - pre-commit               ~= 3.6

